name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.7"]
        plone: ["5.2.x"]
        # exclude:
        #   - python: "3.7"
        #     plone: "51"
    steps:
      - uses: actions/checkout@v1
      - name: Cache eggs
        uses: actions/cache@v1
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          cp test_${{ matrix.plone }}.cfg buildout.cfg
      - name: Install buildout
        run: |
          buildout -N -t 3
      - name: Run tests
        run: |
          bin/test-coverage
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: ${{ matrix.plone }}-${{ matrix.python }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update staging on Rancher
        uses: redturtle/rancher-deploy-action@v0.1.0
        with:
          host: ${{ secrets.RANCHER_HOST }}
          api-username: ${{ secrets.RANCHER_API_USERNAME }}
          api-password: ${{ secrets.RANCHER_API_PASSWORD }}
          cluster-id: ${{ secrets.RANCHER_CLUSTER_ID }}
          project-id: ${{ secrets.RANCHER_PROJECT_ID }}
          namespace: ${{ secrets.RANCHER_NAMESPACE }}
          workload: ${{ secrets.RANCHER_WORKLOAD }}
          image: redturtletech/plone:5.2.4-debian
          slack-hook-url: ${{ secrets.RANCHER_SLACK_HOOK_URL }}

